### ISSUE TITLE
props.joinRoomCallback is not a function

### ISSUE THREAD

**Issue by inderarora1996** [netless-io/react-native-whiteboard#1]
TypeError: props.joinRoomCallback is not a function. (In 'props.joinRoomCallback(undefined, undefined, _context.t0)', 'props.joinRoomCallback' is undefined)

**Comment by leavesster** [comment]
> TypeError: props.joinRoomCallback is not a function. (In 'props.joinRoomCallback(undefined, undefined, _context.t0)', 'props.joinRoomCallback' is undefined)

Thank you for taking the time to report the issue. However, in order for us to better understand and address the problem, we kindly ask you to provide more specific information, such as the steps to reproduce the error, any error messages or logs, and the relevant code snippets or configuration files.

Without this information, it may be difficult for us to identify the root cause of the issue and provide a solution. We appreciate your cooperation and look forward to hearing back from you soon.

**Comment by vince-hz** [comment]
I had try to reproduce your error message.
When I create a WhiteboardView instance without `joinRoomCallback` parameter in props can reproduce your problem.
Please try filling in this parameter to see if it solves.
